KB-128533: adding doc for synthetics create credential
instana/openapi pull request #77
Opened 2023-06-13 18:04 UTC by andreachiavegatto

Adding documentation for the new Synthetics Credential API, showing how the payload looks like, the requirements for credential names and an example.

2023-06-13 18:20 UTC, kmcormick commented on spec/descriptions/createSyntheticCredential.md
> +- **credentialName** The name identifying the credential. Credential names must start with a letter and can only contain letters, numbers and underscores.
Should we mention that the credentialName can be at most 64 characters?

2023-06-13 18:23 UTC, kmcormick commented on spec/descriptions/createSyntheticCredential.md
> +- A sample script to create a simple Ping API test
Since we are not using "Ping" anymore, should this read "A sample script to create an API Simple test"

2023-06-13 18:24 UTC, KarenGdaniec requested changes
We also need to document DELETE credential and any other actions they can do with credetials.  What does GET do?  What does PUT do?  etc.

2023-06-13 18:29 UTC, andreachiavegatto commented
Don't we get the overall doc of the API calls from autogenerated openapi swagger defined on the source code?
I thought we just added the details and samples here. 
@carolzhang65 Could you please confirm.

Note: we do not expose the PUT command to the OpenAPI.

2023-06-13 19:18 UTC, KarenGdaniec commented
I was thinking we should have some note or description about the methods not supported.  Not sure where else we could doc that but in here.  Carol may have an idea how to do it.

2023-06-13 23:05 UTC, carolzhang65 commented
@andreachiavegatto @KarenGdaniec The three Synthetic credential related APIs will show up in the menu. They are auto generated from ui-backend openapi yaml and code. This is a screenshot from my local running OpenAPI site: 
<img width="972" alt="Screenshot 2023-06-13 at 3 49 29 PM" src="https://github.com/instana/openapi/assets/73367095/ae73bc2b-1fec-4548-bb54-f4b13a0d2832">

But in order to see the description in createSyntheticCredential.md, I added the description extension in ui-backend/src/main/java/com/instana/ui/resource/api/synthetics/settings/SyntheticCredentialResource.java and check the changes in Andrea's ui-backend PR: https://github.ibm.com/instana/backend/pull/18703. 
```
@@ -69,7 +71,9 @@ public class SyntheticCredentialResource extends ApiResource {
           @ApiResponse(
               content = @Content(mediaType = "application/json",
                   schema = @Schema(implementation = SyntheticCredentials.class))),
-      }
+      },
+      extensions = @Extension(properties = @ExtensionProperty(name = "description",
+          value = "createSyntheticCredential"))
   )

```

2023-06-13 23:08 UTC, carolzhang65 commented
> I was thinking we should have some note or description about the methods not supported. Not sure where else we could doc that but in here. Carol may have an idea how to do it.

Hi Karen, If an API is not listed in the OpenAPI doc, it means we do not support it. If we need to provide more description, we can add a separate Synthetic Credential section below Synthetic Test Properties.

2023-06-14 12:47 UTC, KarenGdaniec approved these changes

2023-06-14 15:21 UTC, merged