INSTA-3500: Documenting Synthetic SSLCertificate Tests
instana/openapi pull request #98
Opened 2024-05-17 17:49 UTC by andreachiavegatto

2024-05-17 18:01 UTC, ediazgallego requested changes
Looks good overall, small correction for the daysRemainingCheck text

2024-05-17 18:01 UTC, ediazgallego commented on spec/descriptions/tagSyntheticSettings.md
> +          - **daysRemainingCheck** The number of days to use on the validation check. The test will fail when the certificate validity has less this number of days remaining until expiration.
```suggestion
          - **daysRemainingCheck** The number of days to use on the validation check. The test will fail when the certificate validity has less than this number of days remaining until expiration.
```

2024-05-17 18:56 UTC, carolzhang65 commented on spec/descriptions/tagSyntheticSettings.md
> +      BrowserScriptConfiguration, WebpageActionConfiguration, WebpageScriptConfiguration, and SSLCertificateConfiguration (Beta).
```suggestion
      BrowserScriptConfiguration, WebpageActionConfiguration, WebpageScriptConfiguration, and SSLCertificateConfiguration. 
```

2024-05-17 19:02 UTC, carolzhang65 commented on spec/descriptions/tagSyntheticSettings.md
> +      BrowserScriptConfiguration, WebpageActionConfiguration, WebpageScriptConfiguration, and SSLCertificateConfiguration (Beta).
A similar sentence about Synthetic types is also in Location properties part at this [line](https://github.com/instana/openapi/blob/b8bef1f90539cc2625845191d9839b770901f588/spec/descriptions/tagSyntheticSettings.md?plain=1#L11). It needs to be updated too.

2024-05-17 19:09 UTC, ediazgallego approved these changes
:1st_place_medal:  looks good now, thanks!

2024-05-17 19:18 UTC, carolzhang65 reviewed
"testFrequency" range needs to be updated, please state that for SSLCertificate type, the default is every 24 hours. 

In Synthetic result file, I think we'd better to give an example about how to get SSLCertificate custom_metrics data in this [section](https://github.com/instana/openapi/blob/b8bef1f90539cc2625845191d9839b770901f588/spec/descriptions/tagSyntheticResults.md?plain=1#L123).

2024-05-20 16:04 UTC, KarenGdaniec commented on spec/descriptions/tagSyntheticSettings.md
> +    Possible values are HTTPAction, HTTPScript, BrowserScript, WebpageAction, WebpageScript, and SSLCetificate.
```suggestion
    Possible values are HTTPAction, HTTPScript, BrowserScript, WebpageAction, WebpageScript, and SSLCertificate. 
```

2024-05-20 16:06 UTC, KarenGdaniec reviewed
Agree with Carol's comments, good catches.

2024-05-20 16:21 UTC, andreachiavegatto commented
> In Synthetic result file, I think we'd better to give an example about how to get SSLCertificate custom_metrics data in this section

@carolzhang65 There are no examples of the metric returned, just the payload used to query them. 
Should we add one for the SSLCertificate custom metrics?

2024-05-20 19:33 UTC, carolzhang65 approved these changes
The changes look good to me. Thanks.

2024-05-20 19:34 UTC, carolzhang65 commented
> 
> @carolzhang65 There are no examples of the metric returned, just the payload used to query them. Should we add one for the SSLCertificate custom metrics?

No, a sample request payload is good enough. Thanks.

2024-05-21 14:06 UTC, merged